# Generated by Django 3.0.3 on 2020-06-04 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hub_evaluator', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authentication',
            old_name='hub_token',
            new_name='token',
        ),
    ]
